-- 없어진 기록 찾기
SELECT O.ANIMAL_ID, O.NAME
FROM ANIMAL_OUTS O
LEFT OUTER JOIN ANIMAL_INS I
ON I.ANIMAL_ID = O.ANIMAL_ID
WHERE I.ANIMAL_ID IS NULL
ORDER BY O.ANIMAL_ID;

-- 있었는데요 없었습니다
SELECT O.ANIMAL_ID, O.NAME
FROM ANIMAL_OUTS O, ANIMAL_INS I
WHERE O.ANIMAL_ID = I.ANIMAL_ID
AND I.DATETIME > O.DATETIME
AND O.NAME IS NOT NULL
ORDER BY I.DATETIME;

-- 오랜 기간 보호한 동물(1)
SELECT *
FROM (SELECT I.NAME, I.DATETIME
        FROM ANIMAL_INS I
        LEFT OUTER JOIN ANIMAL_OUTS O
        ON I.ANIMAL_ID = O.ANIMAL_ID
        WHERE O.ANIMAL_ID IS NULL
        ORDER BY I.DATETIME)
WHERE ROWNUM < 4;

-- 보호소에서 중성화한 동물
SELECT *
FROM (SELECT I.ANIMAL_ID, I.ANIMAL_TYPE, I.NAME
        FROM ANIMAL_INS I LEFT OUTER JOIN ANIMAL_OUTS O
        ON I.ANIMAL_ID = O.ANIMAL_ID
        WHERE I.SEX_UPON_INTAKE LIKE '%Intact%'
        AND (O.SEX_UPON_OUTCOME LIKE '%Spayed%'
        OR O.SEX_UPON_OUTCOME LIKE '%Neutered%'))
ORDER BY ANIMAL_ID;
